"""remove ratings column

Revision ID: 0cf8ddaf0c03
Revises: 443c54a6e8ff
Create Date: 2026-09-01 17:16:33.666452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0cf8ddaf0c03'
down_revision: Union[str, Sequence[str], None] = '443c54a6e8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ratings', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
