"""Remove salary  column

Revision ID: 2337c803b917
Revises: c1298a1e60fd
Create Date: 2026-09-02 11:27:05.125488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2337c803b917'
down_revision: Union[str, Sequence[str], None] = 'c1298a1e60fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
