"""add ratings column

Revision ID: 443c54a6e8ff
Revises: d06cff7f7f70
Create Date: 2026-09-01 17:09:41.059761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443c54a6e8ff'
down_revision: Union[str, Sequence[str], None] = 'd06cff7f7f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ratings', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ratings')
    # ### end Alembic commands ###
