"""Add salary  column

Revision ID: 915ddd45cd1c
Revises: fae5b63e3dca
Create Date: 2026-09-02 11:05:00.240228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915ddd45cd1c'
down_revision: Union[str, Sequence[str], None] = 'fae5b63e3dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'salary')
    # ### end Alembic commands ###
