"""remove review  column

Revision ID: afca5d66d562
Revises: da47fbeb3cfb
Create Date: 2026-09-01 17:49:23.080259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afca5d66d562'
down_revision: Union[str, Sequence[str], None] = 'da47fbeb3cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
