"""Remove created_at  column

Revision ID: c1298a1e60fd
Revises: 915ddd45cd1c
Create Date: 2026-09-02 11:17:48.768285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1298a1e60fd'
down_revision: Union[str, Sequence[str], None] = '915ddd45cd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
