"""edit department  column

Revision ID: d82ae442b730
Revises: 2337c803b917
Create Date: 2026-09-02 11:32:16.475653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd82ae442b730'
down_revision: Union[str, Sequence[str], None] = '2337c803b917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_name', sa.String(length=15), nullable=False))
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', mysql.VARCHAR(length=15), nullable=False))
    op.drop_column('employees', 'department_name')
    # ### end Alembic commands ###
