"""add review  column

Revision ID: da47fbeb3cfb
Revises: 0cf8ddaf0c03
Create Date: 2026-09-01 17:46:11.197097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da47fbeb3cfb'
down_revision: Union[str, Sequence[str], None] = '0cf8ddaf0c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review')
    # ### end Alembic commands ###
