"""Add created_At column

Revision ID: fae5b63e3dca
Revises: 0e02b871c897
Create Date: 2026-09-02 10:57:42.620945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae5b63e3dca'
down_revision: Union[str, Sequence[str], None] = '0e02b871c897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'created_at')
    # ### end Alembic commands ###
